server:
  port: 8080

spring:
  datasource:
    username: root
    password: 123456
    #url?database?????????????classroom
    url: jdbc:mysql://localhost:3306/gp?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl